# Generated by Django 4.0.4 on 2022-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('coffee', '커피')], default='coffee', max_length=30, unique=True, verbose_name='메뉴')),
                ('stock', models.IntegerField(default=20)),
            ],
        ),
    ]
