# Generated by Django 4.0.4 on 2022-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('coffee', '커피')], default='coffee', max_length=30, unique=True),
        ),
    ]
