# Generated by Django 4.0.4 on 2022-04-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-stock']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
