# Generated by Django 4.0.4 on 2022-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('barista', 'Barista')], default='member', max_length=30),
        ),
    ]
