# Generated by Django 4.0.4 on 2022-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coffee_point',
            field=models.IntegerField(default=10000),
        ),
    ]
