# Generated by Django 4.0.4 on 2022-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_coffee_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coffee_point',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
