# Generated by Django 4.0.4 on 2022-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_coffee_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', '일반멤버'), ('barista', '바리스타')], default='member', max_length=30),
        ),
    ]
