# Generated by Django 4.0.4 on 2022-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=2, max_length=10, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
