# 재고 추가 주기 & 양
STOCK_UPDATE_PERIOD_IN_SEC=60*3
STOCK_UPDATE_AMOUNT=10

# 포인트 추가 주기 & 양
POINT_UPDATE_PERIOD_IN_SEC=60*5
POINT_UPDATE_AMOUNT=10000

# 주문 1건 당 걸리는 랜덤 시간의 최소 & 최대
MIN_SEC_TIME_PER_ORDER=5
MAX_SEC_TIME_PER_ORDER=10
